Feature/4 docker template
yuta10200831/4-docker-template pull request #1
Opened 2023-07-08 14:35 UTC by yuta10200831

## 作業対象
作業をした教材のURL or 作成したページのURLなどを記載する
[作業をした教材のURL]
https://www.notion.so/4-473d583598c3443faea18fb4fa84b861
[作成したページのURL(index.php)]
(http://localhost:8080/)

## 作業詳細
PHP基礎　ビルドイン関数の課題
「$num」の値の小数点以下を切り捨てし出力しましょう。（期待する出力: 3）

<img width="1735" alt="スクリーンショット 2023-07-08 23 34 29" src="https://github.com/yuta10200831/4-docker-template/assets/124555669/704855cb-3a62-4345-b95b-ae5f5ca518ed">

2023-07-09 12:30 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-07-09 12:30 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +echo round($num) ;
切り捨てになっていなそうですね！😭
ブラウザの画面のスクショを貼るようにしましょう！！

2023-07-10 13:15 UTC, yuta10200831 commented on src/public/index.php
> +echo round($num) ;
修正しました！

2023-07-10 13:15 UTC, yuta10200831 commented
修正しました！
ご確認宜しくお願いします！
<img width="1598" alt="スクリーンショット 2023-07-10 22 15 01" src="https://github.com/yuta10200831/4-docker-template/assets/124555669/f3e79ae7-20fe-450c-aad5-26306714a94c">

2023-07-11 04:38 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeいただけると助かります！🙆🙋😊🌟💫

2023-07-11 11:48 UTC, merged